// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbmodels

import (
	"database/sql/driver"
	"fmt"
	"time"

	"scheduler/internal/appointments/domain"
)

type AppointmentsAppointmentStatus string

const (
	AppointmentsAppointmentStatusPending   AppointmentsAppointmentStatus = "pending"
	AppointmentsAppointmentStatusConfirmed AppointmentsAppointmentStatus = "confirmed"
	AppointmentsAppointmentStatusCancelled AppointmentsAppointmentStatus = "cancelled"
)

func (e *AppointmentsAppointmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppointmentsAppointmentStatus(s)
	case string:
		*e = AppointmentsAppointmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AppointmentsAppointmentStatus: %T", src)
	}
	return nil
}

type NullAppointmentsAppointmentStatus struct {
	AppointmentsAppointmentStatus AppointmentsAppointmentStatus
	Valid                         bool // Valid is true if AppointmentsAppointmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppointmentsAppointmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AppointmentsAppointmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppointmentsAppointmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppointmentsAppointmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppointmentsAppointmentStatus), nil
}

type AppointmentsAppointment struct {
	AppointmentUuid  domain.AppointmentUUID
	DealerShipID     string
	ServiceBayID     string
	TechnicianID     string
	UserID           string
	ServiceType      string
	StartTime        time.Time
	EstimatedEndTime time.Time
	Status           domain.AppointmentStatus
	VehicleUuid      domain.VehicleUUID
}

type AppointmentsReservation struct {
	ReservationUuid domain.ReservationUUID
	AppointmentUuid domain.AppointmentUUID
	CreatedAt       time.Time
	ExpiredAt       time.Time
	IdempotencyKey  string
}

type AppointmentsVehicle struct {
	VehicleUuid  domain.VehicleUUID
	UserID       string
	MakeCode     string
	ModelName    string
	ModelYear    int16
	LicensePlate *string
}
