// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation.sql

package dbmodels

import (
	"context"
	"time"

	"scheduler/internal/appointments/domain"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO appointments.reservation (reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key
`

type CreateReservationParams struct {
	ReservationUuid domain.ReservationUUID
	AppointmentUuid domain.AppointmentUUID
	CreatedAt       time.Time
	ExpiredAt       time.Time
	IdempotencyKey  string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ReservationUuid,
		arg.AppointmentUuid,
		arg.CreatedAt,
		arg.ExpiredAt,
		arg.IdempotencyKey,
	)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key FROM appointments.reservation
WHERE idempotency_key = $1
`

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationByUUID = `-- name: GetReservationByUUID :one
SELECT reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key FROM appointments.reservation
WHERE reservation_uuid = $1
`

func (q *Queries) GetReservationByUUID(ctx context.Context, reservationUuid domain.ReservationUUID) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByUUID, reservationUuid)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}
