// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation.sql

package dbmodels

import (
	"context"
	"time"

	"scheduler/internal/appointments/domain"
)

const createReservation = `-- name: CreateReservation :one
INSERT INTO appointments.reservation (reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key
`

type CreateReservationParams struct {
	ReservationUuid domain.ReservationUUID
	AppointmentUuid domain.AppointmentUUID
	CreatedAt       time.Time
	ExpiredAt       time.Time
	IdempotencyKey  string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ReservationUuid,
		arg.AppointmentUuid,
		arg.CreatedAt,
		arg.ExpiredAt,
		arg.IdempotencyKey,
	)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key FROM appointments.reservation
WHERE idempotency_key = $1
`

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationByUUID = `-- name: GetReservationByUUID :one
SELECT reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key FROM appointments.reservation
WHERE reservation_uuid = $1
`

func (q *Queries) GetReservationByUUID(ctx context.Context, reservationUuid domain.ReservationUUID) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByUUID, reservationUuid)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationWithAppointmentByUUID = `-- name: GetReservationWithAppointmentByUUID :one
SELECT
    r.reservation_uuid,
    r.expired_at,
    a.appointment_uuid,
    a.status,
    a.dealer_ship_id,
    a.service_bay_id,
    a.technician_id,
    a.service_type,
    a.vehicle_uuid,
    a.start_time,
    a.estimated_end_time
FROM appointments.reservation r
JOIN appointments.appointment a ON a.appointment_uuid = r.appointment_uuid
WHERE r.reservation_uuid = $1 AND a.user_id = $2
`

type GetReservationWithAppointmentByUUIDParams struct {
	ReservationUuid domain.ReservationUUID
	UserID          string
}

type GetReservationWithAppointmentByUUIDRow struct {
	ReservationUuid  domain.ReservationUUID
	ExpiredAt        time.Time
	AppointmentUuid  domain.AppointmentUUID
	Status           domain.AppointmentStatus
	DealerShipID     string
	ServiceBayID     string
	TechnicianID     string
	ServiceType      string
	VehicleUuid      domain.VehicleUUID
	StartTime        time.Time
	EstimatedEndTime time.Time
}

func (q *Queries) GetReservationWithAppointmentByUUID(ctx context.Context, arg GetReservationWithAppointmentByUUIDParams) (GetReservationWithAppointmentByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationWithAppointmentByUUID, arg.ReservationUuid, arg.UserID)
	var i GetReservationWithAppointmentByUUIDRow
	err := row.Scan(
		&i.ReservationUuid,
		&i.ExpiredAt,
		&i.AppointmentUuid,
		&i.Status,
		&i.DealerShipID,
		&i.ServiceBayID,
		&i.TechnicianID,
		&i.ServiceType,
		&i.VehicleUuid,
		&i.StartTime,
		&i.EstimatedEndTime,
	)
	return i, err
}
