// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation.sql

package dbmodels

import (
	"context"
	"time"

	"scheduler/internal/appointments/domain"
)

const createReservation = `-- name: CreateReservation :exec
INSERT INTO appointments.reservation (reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
`

type CreateReservationParams struct {
	ReservationUuid domain.ReservationUUID
	AppointmentUuid domain.AppointmentUUID
	CreatedAt       time.Time
	ExpiredAt       time.Time
	IdempotencyKey  string
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.Exec(ctx, createReservation,
		arg.ReservationUuid,
		arg.AppointmentUuid,
		arg.CreatedAt,
		arg.ExpiredAt,
		arg.IdempotencyKey,
	)
	return err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key FROM appointments.reservation
WHERE idempotency_key = $1
`

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationByUUID = `-- name: GetReservationByUUID :one
SELECT reservation_uuid, appointment_uuid, created_at, expired_at, idempotency_key FROM appointments.reservation
WHERE reservation_uuid = $1
`

func (q *Queries) GetReservationByUUID(ctx context.Context, reservationUuid domain.ReservationUUID) (AppointmentsReservation, error) {
	row := q.db.QueryRow(ctx, getReservationByUUID, reservationUuid)
	var i AppointmentsReservation
	err := row.Scan(
		&i.ReservationUuid,
		&i.AppointmentUuid,
		&i.CreatedAt,
		&i.ExpiredAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const getReservationWithAppointmentByUUID = `-- name: GetReservationWithAppointmentByUUID :one
SELECT
    r.reservation_uuid, r.appointment_uuid, r.created_at, r.expired_at, r.idempotency_key,
    a.appointment_uuid, a.dealer_ship_id, a.service_bay_id, a.technician_id, a.user_id, a.service_type, a.start_time, a.estimated_end_time, a.status, a.vehicle_uuid
FROM appointments.reservation r
JOIN appointments.appointment a ON a.appointment_uuid = r.appointment_uuid
WHERE r.reservation_uuid = $1 AND a.user_id = $2
`

type GetReservationWithAppointmentByUUIDParams struct {
	ReservationUuid domain.ReservationUUID
	UserID          string
}

type GetReservationWithAppointmentByUUIDRow struct {
	AppointmentsReservation AppointmentsReservation
	AppointmentsAppointment AppointmentsAppointment
}

func (q *Queries) GetReservationWithAppointmentByUUID(ctx context.Context, arg GetReservationWithAppointmentByUUIDParams) (GetReservationWithAppointmentByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getReservationWithAppointmentByUUID, arg.ReservationUuid, arg.UserID)
	var i GetReservationWithAppointmentByUUIDRow
	err := row.Scan(
		&i.AppointmentsReservation.ReservationUuid,
		&i.AppointmentsReservation.AppointmentUuid,
		&i.AppointmentsReservation.CreatedAt,
		&i.AppointmentsReservation.ExpiredAt,
		&i.AppointmentsReservation.IdempotencyKey,
		&i.AppointmentsAppointment.AppointmentUuid,
		&i.AppointmentsAppointment.DealerShipID,
		&i.AppointmentsAppointment.ServiceBayID,
		&i.AppointmentsAppointment.TechnicianID,
		&i.AppointmentsAppointment.UserID,
		&i.AppointmentsAppointment.ServiceType,
		&i.AppointmentsAppointment.StartTime,
		&i.AppointmentsAppointment.EstimatedEndTime,
		&i.AppointmentsAppointment.Status,
		&i.AppointmentsAppointment.VehicleUuid,
	)
	return i, err
}
