// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicle.sql

package dbmodels

import (
	"context"

	"scheduler/internal/appointments/domain"
)

const upsertVehicle = `-- name: UpsertVehicle :exec
INSERT INTO appointments.vehicles (vehicle_uuid, user_id, make_code, model_name, model_year, license_plate)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (vehicle_uuid) DO NOTHING
`

type UpsertVehicleParams struct {
	VehicleUuid  domain.VehicleUUID
	UserID       string
	MakeCode     string
	ModelName    string
	ModelYear    int16
	LicensePlate *string
}

func (q *Queries) UpsertVehicle(ctx context.Context, arg UpsertVehicleParams) error {
	_, err := q.db.Exec(ctx, upsertVehicle,
		arg.VehicleUuid,
		arg.UserID,
		arg.MakeCode,
		arg.ModelName,
		arg.ModelYear,
		arg.LicensePlate,
	)
	return err
}
