// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"scheduler/internal/appointments/domain"

	"github.com/oapi-codegen/runtime"
)

// AppointmentDetailResponse defines model for AppointmentDetailResponse.
type AppointmentDetailResponse struct {
	// AppointmentUuid UUID of the appointment
	AppointmentUuid  AppointmentUUID `json:"appointmentUuid"`
	DealerShipId     string          `json:"dealerShipId"`
	EstimatedEndTime time.Time       `json:"estimatedEndTime"`
	ServiceBayId     string          `json:"serviceBayId"`
	ServiceType      string          `json:"serviceType"`
	StartTime        time.Time       `json:"startTime"`

	// Status Status of the appointment
	Status       AppointmentStatus `json:"status"`
	TechnicianId string            `json:"technicianId"`

	// VehicleUuid UUID of the vehicle
	VehicleUuid VehicleUUID `json:"vehicleUuid"`
}

// AppointmentStatus Status of the appointment
type AppointmentStatus = domain.AppointmentStatus

// AppointmentUUID UUID of the appointment
type AppointmentUUID = domain.AppointmentUUID

// ConfirmBookingResponse defines model for ConfirmBookingResponse.
type ConfirmBookingResponse struct {
	// AppointmentUuid UUID of the appointment
	AppointmentUuid AppointmentUUID `json:"appointmentUuid"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	EntityId   *string `json:"entity_id,omitempty"`
	EntityType *string `json:"entity_type,omitempty"`
	ErrorSlug  *string `json:"error_slug,omitempty"`
	Message    *string `json:"message,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *[]ErrorDetail `json:"details,omitempty"`
	Message string         `json:"message"`
	Slug    string         `json:"slug"`
}

// GetReservationResponse defines model for GetReservationResponse.
type GetReservationResponse struct {
	Appointment AppointmentDetailResponse `json:"appointment"`
	CreatedAt   time.Time                 `json:"createdAt"`
	ExpiredAt   time.Time                 `json:"expiredAt"`

	// ReservationUuid UUID of the reservation
	ReservationUuid ReservationUUID `json:"reservationUuid"`
}

// RequestBookingRequest defines model for RequestBookingRequest.
type RequestBookingRequest struct {
	DealerShipId string                `json:"dealerShipId"`
	ServiceType  string                `json:"serviceType"`
	StartTime    time.Time             `json:"startTime"`
	Vehicle      RequestBookingVehicle `json:"vehicle"`
}

// RequestBookingResponse defines model for RequestBookingResponse.
type RequestBookingResponse struct {
	// ReservationUuid UUID of the reservation
	ReservationUuid ReservationUUID `json:"reservationUuid"`
}

// RequestBookingVehicle defines model for RequestBookingVehicle.
type RequestBookingVehicle struct {
	LicensePlate *string `json:"licensePlate,omitempty"`
	MakeCode     string  `json:"makeCode"`
	ModelName    string  `json:"modelName"`
	ModelYear    int     `json:"modelYear"`
}

// ReservationUUID UUID of the reservation
type ReservationUUID = domain.ReservationUUID

// VehicleUUID UUID of the vehicle
type VehicleUUID = domain.VehicleUUID

// CancelBookingParams defines parameters for CancelBooking.
type CancelBookingParams struct {
	XUserId *string `json:"X-User-Id,omitempty"`
}

// RequestBookingParams defines parameters for RequestBooking.
type RequestBookingParams struct {
	XUserId        *string `json:"X-User-Id,omitempty"`
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// GetReservationParams defines parameters for GetReservation.
type GetReservationParams struct {
	XUserId *string `json:"X-User-Id,omitempty"`
}

// ConfirmBookingParams defines parameters for ConfirmBooking.
type ConfirmBookingParams struct {
	XUserId *string `json:"X-User-Id,omitempty"`
}

// RequestBookingJSONRequestBody defines body for RequestBooking for application/json ContentType.
type RequestBookingJSONRequestBody = RequestBookingRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// CancelBooking Cancel booking
	//
	// Cancel a confirmed appointment.
	//
	// Corresponds with PUT /appointments/{appointment_uuid} (the `CancelBooking` operationId).
	CancelBooking(ctx context.Context, appointmentUuid AppointmentUUID, params *CancelBookingParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RequestBookingWithBody Request booking
	//
	// Request a booking, holding a technician and service bay with a reservation
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /reservations (the `RequestBooking` operationId).
	RequestBookingWithBody(ctx context.Context, params *RequestBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RequestBooking Request booking
	//
	// Request a booking, holding a technician and service bay with a reservation
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /reservations (the `RequestBooking` operationId).
	RequestBooking(ctx context.Context, params *RequestBookingParams, body RequestBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReservation Get reservation
	//
	// Get a reservation together with its appointment.
	//
	// Corresponds with GET /reservations/{reservation_uuid} (the `GetReservation` operationId).
	GetReservation(ctx context.Context, reservationUuid ReservationUUID, params *GetReservationParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ConfirmBooking Confirm booking
	//
	// Confirm a pending appointment using its reservation.
	//
	// Corresponds with PUT /reservations/{reservation_uuid} (the `ConfirmBooking` operationId).
	ConfirmBooking(ctx context.Context, reservationUuid ReservationUUID, params *ConfirmBookingParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// CancelBooking Cancel booking
//
// Cancel a confirmed appointment.
//
// Corresponds with PUT /appointments/{appointment_uuid} (the `CancelBooking` operationId).
func (c *Client) CancelBooking(ctx context.Context, appointmentUuid AppointmentUUID, params *CancelBookingParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCancelBookingRequest(c.Server, appointmentUuid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RequestBookingWithBody Request booking
//
// # Request a booking, holding a technician and service bay with a reservation
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /reservations (the `RequestBooking` operationId).
func (c *Client) RequestBookingWithBody(ctx context.Context, params *RequestBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestBookingRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RequestBooking Request booking
//
// # Request a booking, holding a technician and service bay with a reservation
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /reservations (the `RequestBooking` operationId).
func (c *Client) RequestBooking(ctx context.Context, params *RequestBookingParams, body RequestBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRequestBookingRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetReservation Get reservation
//
// Get a reservation together with its appointment.
//
// Corresponds with GET /reservations/{reservation_uuid} (the `GetReservation` operationId).
func (c *Client) GetReservation(ctx context.Context, reservationUuid ReservationUUID, params *GetReservationParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReservationRequest(c.Server, reservationUuid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ConfirmBooking Confirm booking
//
// Confirm a pending appointment using its reservation.
//
// Corresponds with PUT /reservations/{reservation_uuid} (the `ConfirmBooking` operationId).
func (c *Client) ConfirmBooking(ctx context.Context, reservationUuid ReservationUUID, params *ConfirmBookingParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewConfirmBookingRequest(c.Server, reservationUuid, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCancelBookingRequest constructs an http.Request for the CancelBooking method
func NewCancelBookingRequest(server string, appointmentUuid AppointmentUUID, params *CancelBookingParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "appointment_uuid", appointmentUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/appointments/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XUserId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-User-Id", *params.XUserId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-User-Id", headerParam0)
		}

	}

	return req, nil
}

// NewRequestBookingRequest calls the generic RequestBooking builder with application/json body
func NewRequestBookingRequest(server string, params *RequestBookingParams, body RequestBookingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRequestBookingRequestWithBody(server, params, "application/json", bodyReader)
}

// NewRequestBookingRequestWithBody constructs an http.Request for the RequestBooking method, with any body, and a specified content type
func NewRequestBookingRequestWithBody(server string, params *RequestBookingParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XUserId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-User-Id", *params.XUserId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-User-Id", headerParam0)
		}

		if params.IdempotencyKey != nil {
			var headerParam1 string

			headerParam1, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam1)
		}

	}

	return req, nil
}

// NewGetReservationRequest constructs an http.Request for the GetReservation method
func NewGetReservationRequest(server string, reservationUuid ReservationUUID, params *GetReservationParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "reservation_uuid", reservationUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XUserId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-User-Id", *params.XUserId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-User-Id", headerParam0)
		}

	}

	return req, nil
}

// NewConfirmBookingRequest constructs an http.Request for the ConfirmBooking method
func NewConfirmBookingRequest(server string, reservationUuid ReservationUUID, params *ConfirmBookingParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "reservation_uuid", reservationUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/reservations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XUserId != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "X-User-Id", *params.XUserId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-User-Id", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// CancelBookingWithResponse Cancel booking
	//
	// Cancel a confirmed appointment.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /appointments/{appointment_uuid} (the `CancelBooking` operationId).
	CancelBookingWithResponse(ctx context.Context, appointmentUuid AppointmentUUID, params *CancelBookingParams, reqEditors ...RequestEditorFn) (*CancelBookingClientResponse, error)

	// RequestBookingWithBodyWithResponse Request booking
	//
	// Request a booking, holding a technician and service bay with a reservation
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /reservations (the `RequestBooking` operationId).
	RequestBookingWithBodyWithResponse(ctx context.Context, params *RequestBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestBookingClientResponse, error)

	// RequestBookingWithResponse Request booking
	//
	// Request a booking, holding a technician and service bay with a reservation
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /reservations (the `RequestBooking` operationId).
	RequestBookingWithResponse(ctx context.Context, params *RequestBookingParams, body RequestBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestBookingClientResponse, error)

	// GetReservationWithResponse Get reservation
	//
	// Get a reservation together with its appointment.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /reservations/{reservation_uuid} (the `GetReservation` operationId).
	GetReservationWithResponse(ctx context.Context, reservationUuid ReservationUUID, params *GetReservationParams, reqEditors ...RequestEditorFn) (*GetReservationClientResponse, error)

	// ConfirmBookingWithResponse Confirm booking
	//
	// Confirm a pending appointment using its reservation.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /reservations/{reservation_uuid} (the `ConfirmBooking` operationId).
	ConfirmBookingWithResponse(ctx context.Context, reservationUuid ReservationUUID, params *ConfirmBookingParams, reqEditors ...RequestEditorFn) (*ConfirmBookingClientResponse, error)
}

type CancelBookingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CancelBookingClientResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CancelBookingClientResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r CancelBookingClientResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CancelBookingClientResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r CancelBookingClientResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r CancelBookingClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CancelBookingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CancelBookingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CancelBookingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RequestBookingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *RequestBookingResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r RequestBookingClientResponse) GetJSON201() *RequestBookingResponse {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r RequestBookingClientResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r RequestBookingClientResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r RequestBookingClientResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r RequestBookingClientResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r RequestBookingClientResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r RequestBookingClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RequestBookingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RequestBookingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RequestBookingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetReservationClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetReservationResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetReservationClientResponse) GetJSON200() *GetReservationResponse {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetReservationClientResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetReservationClientResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetReservationClientResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetReservationClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetReservationClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReservationClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetReservationClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ConfirmBookingClientResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ConfirmBookingResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON410 the response for an HTTP 410 `application/json` response
	JSON410 *ErrorResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ConfirmBookingClientResponse) GetJSON200() *ConfirmBookingResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ConfirmBookingClientResponse) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ConfirmBookingClientResponse) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ConfirmBookingClientResponse) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r ConfirmBookingClientResponse) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON410 returns the response for an HTTP 410 `application/json` response
func (r ConfirmBookingClientResponse) GetJSON410() *ErrorResponse {
	return r.JSON410
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ConfirmBookingClientResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ConfirmBookingClientResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ConfirmBookingClientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ConfirmBookingClientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ConfirmBookingClientResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CancelBookingWithResponse Cancel booking
//
// Cancel a confirmed appointment.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /appointments/{appointment_uuid} (the `CancelBooking` operationId).
func (c *ClientWithResponses) CancelBookingWithResponse(ctx context.Context, appointmentUuid AppointmentUUID, params *CancelBookingParams, reqEditors ...RequestEditorFn) (*CancelBookingClientResponse, error) {
	rsp, err := c.CancelBooking(ctx, appointmentUuid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCancelBookingClientResponse(rsp)
}

// RequestBookingWithBodyWithResponse Request booking
//
// # Request a booking, holding a technician and service bay with a reservation
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /reservations (the `RequestBooking` operationId).
func (c *ClientWithResponses) RequestBookingWithBodyWithResponse(ctx context.Context, params *RequestBookingParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RequestBookingClientResponse, error) {
	rsp, err := c.RequestBookingWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestBookingClientResponse(rsp)
}

// RequestBookingWithResponse Request booking
//
// # Request a booking, holding a technician and service bay with a reservation
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /reservations (the `RequestBooking` operationId).
func (c *ClientWithResponses) RequestBookingWithResponse(ctx context.Context, params *RequestBookingParams, body RequestBookingJSONRequestBody, reqEditors ...RequestEditorFn) (*RequestBookingClientResponse, error) {
	rsp, err := c.RequestBooking(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRequestBookingClientResponse(rsp)
}

// GetReservationWithResponse Get reservation
//
// Get a reservation together with its appointment.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /reservations/{reservation_uuid} (the `GetReservation` operationId).
func (c *ClientWithResponses) GetReservationWithResponse(ctx context.Context, reservationUuid ReservationUUID, params *GetReservationParams, reqEditors ...RequestEditorFn) (*GetReservationClientResponse, error) {
	rsp, err := c.GetReservation(ctx, reservationUuid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReservationClientResponse(rsp)
}

// ConfirmBookingWithResponse Confirm booking
//
// Confirm a pending appointment using its reservation.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /reservations/{reservation_uuid} (the `ConfirmBooking` operationId).
func (c *ClientWithResponses) ConfirmBookingWithResponse(ctx context.Context, reservationUuid ReservationUUID, params *ConfirmBookingParams, reqEditors ...RequestEditorFn) (*ConfirmBookingClientResponse, error) {
	rsp, err := c.ConfirmBooking(ctx, reservationUuid, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseConfirmBookingClientResponse(rsp)
}

// ParseCancelBookingClientResponse parses an HTTP response from a CancelBookingWithResponse call
func ParseCancelBookingClientResponse(rsp *http.Response) (*CancelBookingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CancelBookingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseRequestBookingClientResponse parses an HTTP response from a RequestBookingWithResponse call
func ParseRequestBookingClientResponse(rsp *http.Response) (*RequestBookingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RequestBookingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RequestBookingResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetReservationClientResponse parses an HTTP response from a GetReservationWithResponse call
func ParseGetReservationClientResponse(rsp *http.Response) (*GetReservationClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReservationClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetReservationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseConfirmBookingClientResponse parses an HTTP response from a ConfirmBookingWithResponse call
func ParseConfirmBookingClientResponse(rsp *http.Response) (*ConfirmBookingClientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ConfirmBookingClientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConfirmBookingResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 410:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON410 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
